---
- name: Database Server Setup
  hosts: db_srv
  become: yes
  tasks:
    - name: Install MariaDB server
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install Python MySQL dependencies
      ansible.builtin.package:
        name: python3-pymysql
        state: present
    
    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create MySQL User 'gadiel'
      community.mysql.mysql_user:
        name: gadiel
        password: 'admin2020'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        column_case_sensitive: false
        
        
        
