---
- name: Database Server Setup
  hosts: db_srv
  become: yes
  vars:
    dbname: electric
    dbuser: current
    dbpass: tesla 
  tasks:
    - debug:
        msg: "The dbname is {{dbname}}"

    - debug:
        var: dbuser

    - name: Install MariaDB server
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install Python MySQL dependencies
      ansible.builtin.package:
        name: python3-pymysql
        state: present
    
    - name: Create a new database
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create MySQL User 'gadiel'
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
        column_case_sensitive: false
      register: dbout

    - name: print dbout variable
      debug:
        var: dbout
        
        
        
