---
- hosts: all
  become: yes
  tasks:

    - name: Install Nginx and update package cache (Ubuntu)
      apt:
        name:
          - nginx
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache and PHP (CentOS)
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Start and enable Apache (CentOS)
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Open port 80 in the firewall (CentOS)
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: Reload firewall to apply changes (CentOS)
      command: firewall-cmd --reload
      when: ansible_distribution == "CentOS"
