---
- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
  
    - name: Install MariaDB server
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Install Python MySQL module (PyMySQL)
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Start MariaDB service and enable on boot
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_user: root
        login_password: "osboxes.org"  # Replace with actual root password

