---
- name: Webserver setup
  hosts: web_srv
  become: yes
  tasks:
    - name: Install Apache (httpd for RedHat, apache2 for Debian)
      ansible.builtin.package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: present

    - name: Start and enable the web server
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes

- name: DB Server Setup
  hosts: db_srv
  become: yes
  tasks:
    - name: Install MariaDB server
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
