---
- name: Webserver setup
  hosts: web_srv
  become: yes
  tasks:
    - name: Install Apache (httpd for RedHat, apache2 for Debian)
      ansible.builtin.package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: present

    - name: Start and enable the web server
      ansible.builtin.service:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes

   - name: Copy file index file
     copy:
       src: files/index.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: '0644'

